# Generated by Django 2.2.4 on 2020-12-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt_pass',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
