# Generated by Django 2.2.4 on 2020-12-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user_salt_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salt_pass',
        ),
    ]
