# Generated by Django 2.2.4 on 2020-12-28 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_user_salt_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('entry', models.DecimalField(decimal_places=2, max_digits=7)),
                ('exit', models.DecimalField(decimal_places=2, max_digits=7)),
                ('position_size', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_buy', models.BooleanField()),
                ('trade_pattern', models.CharField(max_length=55)),
                ('sector', models.CharField(max_length=55)),
                ('dateOfTrade', models.DateField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_sector',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='app1.User'),
        ),
    ]
