# Generated by Django 2.2.4 on 2021-01-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20201228_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='vault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('sector', models.CharField(max_length=55)),
                ('open', models.DecimalField(decimal_places=2, max_digits=7)),
                ('high', models.DecimalField(decimal_places=2, max_digits=7)),
                ('low', models.DecimalField(decimal_places=2, max_digits=7)),
                ('close', models.DecimalField(decimal_places=2, max_digits=7)),
                ('previous_close', models.DecimalField(decimal_places=2, max_digits=7)),
                ('volume', models.IntegerField()),
                ('float', models.IntegerField()),
                ('catalyst', models.CharField(max_length=55)),
                ('lookupdate', models.DateField()),
                ('year_high', models.DecimalField(decimal_places=2, max_digits=7)),
                ('year_low', models.DecimalField(decimal_places=2, max_digits=7)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
