# Generated by Django 2.2.4 on 2021-01-13 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20210111_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockvault',
            name='catalyst',
        ),
        migrations.RemoveField(
            model_name='stockvault',
            name='lookUpDate',
        ),
        migrations.AddField(
            model_name='stockvault',
            name='pattern',
            field=models.CharField(default='None', max_length=55),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockHistory', to='app1.User'),
        ),
    ]
