# Generated by Django 2.2.4 on 2021-01-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20210112_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockvault',
            name='exchange',
            field=models.CharField(default='None', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockvault',
            name='industry',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
