# Generated by Django 2.2.4 on 2021-02-06 21:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20210113_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockvault',
            name='daychart',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=20), size=None), default=[], size=None),
            preserve_default=False,
        ),
    ]
