# Generated by Django 2.2.4 on 2021-03-05 00:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_stockvault_daychart'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockWatchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('desc', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('catalyst', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='vault',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='stock',
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockvault',
            name='type',
            field=models.CharField(default=[], max_length=10),
        ),
        migrations.AddField(
            model_name='stockvault',
            name='vault',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='stockVault', to='app1.vault'),
        ),
        migrations.AlterField(
            model_name='vault',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uservault', to='app1.User'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_watchlist', to='app1.User'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AddField(
            model_name='stockwatchlist',
            name='watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='app1.Watchlist'),
        ),
    ]
