# Generated by Django 2.2.4 on 2021-03-05 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20210304_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockwatchlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
