# Generated by Django 2.2.4 on 2021-03-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_stockwatchlist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockwatchlist',
            name='catalyst',
            field=models.CharField(max_length=45),
        ),
    ]
