# Generated by Django 2.2.4 on 2021-05-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_watchlist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
